export interface Recipe {
  id: string
  title: string
  description: string
  image: string
  time: string
  servings: string
  difficulty: string
  ingredients: string[]
  steps: string[]
}

export const recipes: Recipe[] = [
  {
    id: "fluffy-pancakes",
    title: "Fluffy Pancakes",
    description: "Light and airy pancakes perfect for breakfast. Golden brown exterior with a soft, tender interior.",
    image: "/stack-of-fluffy-golden-pancakes-with-butter-and-sy.jpg",
    time: "20 min",
    servings: "4",
    difficulty: "Easy",
    ingredients: [
      "2 cups all-purpose flour",
      "2 tablespoons sugar",
      "2 teaspoons baking powder",
      "1 teaspoon salt",
      "2 cups milk",
      "2 large eggs",
      "4 tablespoons melted butter",
      "1 teaspoon vanilla extract",
    ],
    steps: [
      "In a large bowl, whisk together flour, sugar, baking powder, and salt.",
      "In another bowl, beat eggs and add milk, melted butter, and vanilla extract.",
      "Pour wet ingredients into dry ingredients and mix until just combined. Do not overmix.",
      "Heat a non-stick pan or griddle over medium heat and lightly grease.",
      "Pour 1/4 cup of batter for each pancake onto the griddle.",
      "Cook until bubbles form on surface and edges look set, about 2-3 minutes.",
      "Flip and cook until golden brown on the other side, about 2 minutes more.",
      "Serve hot with butter and maple syrup.",
    ],
  },
  {
    id: "garlic-butter-shrimp",
    title: "Garlic Butter Shrimp",
    description: "Restaurant-quality shrimp in a rich garlic butter sauce. Ready in under 15 minutes.",
    image: "/sauteed-shrimp-in-garlic-butter-sauce-with-parsley.jpg",
    time: "15 min",
    servings: "4",
    difficulty: "Easy",
    ingredients: [
      "1 lb large shrimp, peeled and deveined",
      "4 tablespoons butter",
      "4 cloves garlic, minced",
      "1/4 cup white wine",
      "2 tablespoons lemon juice",
      "1/4 teaspoon red pepper flakes",
      "Salt and pepper to taste",
      "2 tablespoons fresh parsley, chopped",
    ],
    steps: [
      "Pat shrimp dry with paper towels and season with salt and pepper.",
      "Melt butter in a large skillet over medium-high heat.",
      "Add minced garlic and cook for 30 seconds until fragrant.",
      "Add shrimp to the pan in a single layer and cook for 2 minutes per side.",
      "Add white wine, lemon juice, and red pepper flakes.",
      "Cook for another 2 minutes until shrimp are pink and opaque.",
      "Remove from heat and stir in fresh parsley.",
      "Serve immediately with crusty bread or over pasta.",
    ],
  },
  {
    id: "classic-chocolate-chip-cookies",
    title: "Chocolate Chip Cookies",
    description:
      "The ultimate chocolate chip cookie recipe. Crispy edges with a soft, chewy center loaded with chocolate.",
    image: "/chocolate-chip-cookies-stacked-with-melted-chocola.jpg",
    time: "30 min",
    servings: "24 cookies",
    difficulty: "Easy",
    ingredients: [
      "2 1/4 cups all-purpose flour",
      "1 teaspoon baking soda",
      "1 teaspoon salt",
      "1 cup butter, softened",
      "3/4 cup granulated sugar",
      "3/4 cup brown sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "2 cups chocolate chips",
    ],
    steps: [
      "Preheat oven to 375°F (190°C).",
      "Mix flour, baking soda, and salt in a bowl.",
      "In another bowl, cream together butter and both sugars until fluffy.",
      "Beat in eggs one at a time, then stir in vanilla.",
      "Gradually blend in the flour mixture.",
      "Fold in chocolate chips until evenly distributed.",
      "Drop rounded tablespoons of dough onto ungreased cookie sheets.",
      "Bake for 9-11 minutes or until golden brown.",
      "Cool on baking sheet for 2 minutes, then transfer to a wire rack.",
    ],
  },
  {
    id: "chicken-stir-fry",
    title: "Chicken Stir Fry",
    description: "Quick and healthy stir fry with tender chicken and crisp vegetables in a savory sauce.",
    image: "/colorful-chicken-stir-fry-with-vegetables-in-a-wok.jpg",
    time: "25 min",
    servings: "4",
    difficulty: "Medium",
    ingredients: [
      "1 lb chicken breast, sliced thin",
      "2 tablespoons vegetable oil",
      "1 bell pepper, sliced",
      "1 cup broccoli florets",
      "1 carrot, julienned",
      "3 cloves garlic, minced",
      "1/4 cup soy sauce",
      "2 tablespoons oyster sauce",
      "1 tablespoon cornstarch",
      "1/4 cup water",
    ],
    steps: [
      "Mix soy sauce, oyster sauce, cornstarch, and water in a small bowl.",
      "Heat 1 tablespoon oil in a wok or large pan over high heat.",
      "Add chicken and stir-fry for 5-6 minutes until cooked through. Remove and set aside.",
      "Add remaining oil and stir-fry garlic for 30 seconds.",
      "Add all vegetables and stir-fry for 3-4 minutes until crisp-tender.",
      "Return chicken to the pan.",
      "Pour sauce over everything and toss to coat.",
      "Cook for 2 minutes until sauce thickens.",
      "Serve hot over rice or noodles.",
    ],
  },
  {
    id: "caprese-salad",
    title: "Caprese Salad",
    description: "Fresh tomatoes, mozzarella, and basil drizzled with balsamic glaze. Simple Italian perfection.",
    image: "/caprese-salad-with-tomatoes-mozzarella-and-basil.jpg",
    time: "10 min",
    servings: "4",
    difficulty: "Easy",
    ingredients: [
      "4 large ripe tomatoes",
      "16 oz fresh mozzarella",
      "1 cup fresh basil leaves",
      "1/4 cup extra virgin olive oil",
      "3 tablespoons balsamic glaze",
      "Salt and black pepper to taste",
      "Flaky sea salt for garnish",
    ],
    steps: [
      "Slice tomatoes and mozzarella into 1/4-inch thick rounds.",
      "Arrange tomato and mozzarella slices alternately on a serving platter.",
      "Tuck fresh basil leaves between the slices.",
      "Drizzle with extra virgin olive oil.",
      "Drizzle with balsamic glaze in a decorative pattern.",
      "Season with salt and freshly ground black pepper.",
      "Finish with a sprinkle of flaky sea salt.",
      "Let sit for 5 minutes before serving to allow flavors to meld.",
    ],
  },
  {
    id: "banana-bread",
    title: "Classic Banana Bread",
    description: "Moist and flavorful banana bread made with overripe bananas. Perfect for breakfast or snacking.",
    image: "/sliced-banana-bread-loaf-with-walnuts.jpg",
    time: "1 hr 15 min",
    servings: "8 slices",
    difficulty: "Easy",
    ingredients: [
      "3 ripe bananas, mashed",
      "1/3 cup melted butter",
      "3/4 cup sugar",
      "1 egg, beaten",
      "1 teaspoon vanilla extract",
      "1 teaspoon baking soda",
      "1/4 teaspoon salt",
      "1 1/2 cups all-purpose flour",
      "1/2 cup chopped walnuts (optional)",
    ],
    steps: [
      "Preheat oven to 350°F (175°C). Grease a 9x5 inch loaf pan.",
      "In a large bowl, mash the ripe bananas with a fork.",
      "Mix in melted butter until well combined.",
      "Stir in sugar, beaten egg, and vanilla extract.",
      "Sprinkle baking soda and salt over the mixture and mix in.",
      "Add flour and stir until just incorporated. Do not overmix.",
      "Fold in chopped walnuts if using.",
      "Pour batter into prepared loaf pan.",
      "Bake for 60-65 minutes until a toothpick comes out clean.",
      "Cool in pan for 10 minutes, then turn out onto a wire rack.",
    ],
  },
]
